/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Chapter12Native_java_HelloJNI */

#ifndef _Included_Chapter12Native_java_HelloJNI
#define _Included_Chapter12Native_java_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Chapter12Native_java_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Chapter12Native_java_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
